"""Write ONNX_VARIANTS.md from results/onnx_variants/*.json (see run.py).

Run from the repo root:
    <privaite venv>/bin/python -m scripts.onnx_variants.report
"""

from __future__ import annotations

import json

from benchlib.paths import BENCH, RESULTS

REFERENCE = "q4f16"
ORDER = ["q4", "q4f16", "quantized"]


def provenance(run: dict) -> str:
    """Which PrivAiTe the numbers come from. A run taken before the version bump
    carries `engine_released_as`: the code under test shipped as that release
    while its version string still read the previous one."""
    released = run.get("engine_released_as")
    if released and released != run["privaite"]:
        return (f"Generated by `scripts/onnx_variants/` with the engine released as privaite {released} "
                f"(its version string still read {run['privaite']} when measured; each run sets the "
                "variant explicitly, so the default does not affect the numbers).")
    return f"Generated by `scripts/onnx_variants/` with privaite {run['privaite']}."


def main() -> None:
    runs = {}
    for variant in ORDER:
        path = RESULTS / "onnx_variants" / f"{variant}.json"
        if path.exists():
            runs[variant] = json.loads(path.read_text())
    ref = runs[REFERENCE]

    lines = [
        "# ONNX variants of the Privacy Filter",
        "",
        "PrivAiTe's `onnx` preset with only `pii.detectors.onnx.onnx_variant` changed, on the",
        "same corpora as [`COMPARISON.md`](COMPARISON.md) and",
        "[`OOD_COMPARISON.md`](OOD_COMPARISON.md), CPU execution provider. `q4` and `q4f16`",
        "hold the same 4-bit weights; `q4` computes in fp32 and `q4f16` in fp16, which CPUs",
        "do not run natively. `quantized` is the int8 export.",
        "",
        provenance(ref),
        "",
        "## Result",
        "",
        "| Variant | Recall | Recall (strict) | False positives | Gretel recall | Full benchmark | Gretel | "
        "One 1,024-token window | Peak memory |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for variant, r in runs.items():
        b, g = r["bench"], r["gretel"]
        lines.append(
            f"| `{variant}` | {b['recall']}% | {b['recall_token_level']}% | {b['false_positives']} / "
            f"{b['clean_docs']} | {g['recall']}% | {r['bench_seconds']:.0f} s | {g['seconds']:.0f} s | "
            f"{r['window_seconds']['1024'] * 1000:,.0f} ms | {r['peak_rss_gb']} GB |"
        )

    ratio_path = RESULTS / "onnx_variants" / "window_ratio.json"
    if ratio_path.exists():
        ratio = json.loads(ratio_path.read_text())
        lines += ["", "## Cost of one window, variants alternating", "",
                  "Each variant's session is loaded once and the calls alternate between them, so "
                  "ambient load on the machine hits all three the same way "
                  f"({ratio['rounds']} rounds, median).", "",
                  "| Variant | 512 tokens | vs `q4f16` | 1,024 tokens | vs `q4f16` |", "|---|---|---|---|---|"]
        for variant in ORDER:
            r = ratio["variants"][variant]
            lines.append(
                f"| `{variant}` | {r['512']['median_s'] * 1000:,.0f} ms | x{r['512']['ratio_vs_q4f16']} | "
                f"{r['1024']['median_s'] * 1000:,.0f} ms | x{r['1024']['ratio_vs_q4f16']} |"
            )

    lines += ["", "## Agreement with `q4f16`", "",
              "| Variant | Identical outputs | Labelled values caught that `q4f16` missed | "
              "Labelled values `q4f16` caught that this variant missed |",
              "|---|---|---|---|"]
    for variant, r in runs.items():
        if variant == REFERENCE:
            continue
        digests = ref["output_digests"]
        same = sum(1 for k, d in digests.items() if r["output_digests"].get(k) == d)
        gained = lost = 0
        for doc, ref_leaks in ref["leaked_labelled_value_digests"].items():
            mine = set(r["leaked_labelled_value_digests"].get(doc, []))
            gained += len(set(ref_leaks) - mine)
            lost += len(mine - set(ref_leaks))
        lines.append(f"| `{variant}` | {same} / {len(digests)} | {gained} | {lost} |")

    lines += ["", "## Long inputs (seconds)", "", "| Input | " + " | ".join(f"`{v}`" for v in runs) + " |",
              "|---|" + "---|" * len(runs)]
    for name, info in ref["long_inputs"].items():
        cells = " | ".join(f"{r['long_inputs'][name]['seconds']}" for r in runs.values())
        lines.append(f"| {name}, {info['chars']:,} chars | {cells} |")

    lines += [
        "",
        "## Caveats",
        "",
        "- Measured on one Apple Silicon machine. x86 and GPU sessions were not measured; fp16",
        "  is where a GPU is expected to favour `q4f16`.",
        "- Each variant ran in its own process on a machine that was not idle, so the absolute",
        "  durations in the first table move with the load and fall unevenly on the variants: the",
        "  full benchmark ratio there is larger than the alternating one for that reason. The",
        "  alternating measurement is the load-independent one; read the ratios, not the seconds.",
        "- The full benchmark time includes Presidio, and peak memory is the whole process with",
        "  four spaCy languages loaded.",
        "- Outputs are compared by hash; the corpora are rebuilt locally and not redistributed.",
        "",
    ]
    (BENCH / "ONNX_VARIANTS.md").write_text("\n".join(lines))
    print("wrote ONNX_VARIANTS.md")


if __name__ == "__main__":
    main()
